### ISSUE TITLE
Mobs like to jump into lava

### ISSUE THREAD

**Issue by varencilator** [miyo6032/mobs-attempt-parkour#4]
Mobs try to jump over lava that's on ground level (1 block high). I assume they try to jump over the obstacle  but it never works. Maybe let them recognize lava and not try to jump past it? They actually seem to just try to walk through it even

**Comment by barribob** [comment]
Thanks for reporting. I will investigate further at some point.

**Comment by varencilator** [comment]
They also jump on fire I've noticed

**Comment by barribob** [comment]
Having a hard time replicating - if you are still tracking this, would you be able to get some screenshots?

**Comment by varencilator** [comment]
I tested the mod by itself and I don't believe it's this mod unless it's some interaction with another mod so I'll close it for now. Tried taking it out and it didn't change the issue so it's definitely not this mod, sorry!
