### ISSUE TITLE
Update Plz

### ISSUE THREAD

**Issue by ask6155** [miyo6032/mobs-attempt-parkour#5]
Please update mod to 1.17.1 so I can add it to my modpack.
I want to scare my friends.

**Comment by barribob** [comment]
It works for 1.17.1 AFAIK - please elaborate on what you are encountering

**Comment by ask6155** [comment]
On modrinth it says it only support 1.16.5

**Comment by barribob** [comment]
Ah, yes, I haven't been looking at modrinth - will fix that sometime this week
