### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [miyo6032/mobs-attempt-parkour#6]
Hello, I was loading the latest version on my 1.19.3 server.
No issues so far - I think it's compatible.

**Comment by barribob** [comment]
It won't run on its own - maybe if you ran it with BOMD it would work. Will actually update when 1.19.4 arrives

**Comment by sternschnaube** [comment]
Oh oki, no I don't run it with BOMD.
Good to know, thank you.

No hope for a 1.19.3 release?
